Repository jun-koyama-h/team_project, pull requests merged in 2024-01, with the labels that each got.

#187 README追加　使用するメディア 12か国
  README.md
Labels: survey

#217 検索ボックスに削除ボタンを入れた
  news-on-earth/src/assets/clear.svg
  news-on-earth/src/views/SearchBox.tsx
  news-on-earth/src/views/SearchPage.module.css
Labels: enhancement

#270 bugfix: Potentially unsafe external link. #269
  news-on-earth/src/views/SearchResult.tsx
Labels: bug
